from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^notifications/$',
        view=views.notifications,
        name='notifications'
    ),

    url(
        regex=r'^dashboard/$',
        view=views.dashboard,
        name='dashboard'
    ),
    url(
        regex=r'^server/update/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerUpdateView.as_view(),
        name='server_update'
    ),
    url(
        regex=r'^server/delete/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerDeleteView.as_view(),
        name='server_delete'
    ),
    url(
        regex=r'^server/show/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.ServerShowView.as_view(),
        name='server_show'
    ),
    url(
        regex=r'^server/kpis/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.serverkpis,
        name='server_kpis'
    ),
    url(
        regex=r'^server/(?P<pk>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/alerts/list/$',
        view=views.EventListView.as_view(),
        name='server_alerts'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.server,
        name='server'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/process/(?P<process_name>[^/]+)/$',
        view=views.process,
        name='process'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/filesystem/(?P<filesystem_id>[^/]+)/$',
        view=views.filesystem,
        name='filesystem'
    ),
    url(
        regex=r'^server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/network/(?P<network_name>[^/]+)/$',
        view=views.network,
        name='network'
    ),
    url(
        regex=r'^confirm_delete/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.confirm_delete,
        name='confirm_delete'
    ),
    url(
        regex=r'^delete_server/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.delete_server,
        name='delete_server'
    ),

    url(
        regex=r'^load_system_data/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.load_system_data,
        name='load_system_data'
    ),
    url(
        regex=r'^load_process_data/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<process_name>[^/]+)/$',
        view=views.load_process_data,
        name='load_process_data'
    ),
    url(
        regex=r'^load_network_data/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<net_name>[^/]+)/$',
        view=views.load_network_data,
        name='load_network_data'
    ),
    url(
        regex=r'^load_dashboard_table/$',
        view=views.load_dashboard_table,
        name='load_dashboard_table'
    ),
    url(
        regex=r'^load_system_table/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/$',
        view=views.load_system_table,
        name='load_system_table'
    ),
    url(
        regex=r'^load_process_table/(?P<server_id>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/(?P<process_name>[^/]+)/$',
        view=views.load_process_table,
        name='load_process_table'
    ),
    url(
        regex=r'ackevent/$',
        view=views.ack_event,
        name='ack_event'
    ),

    url(
        regex=r'settings/(?P<pk>.*)/$$',
        view=views.SettingsUpdateView.as_view(),
        name='settings_update'
    ),
    url(
        regex=r'intellievent/$',
        view=views.IntelliEvent.as_view(),
        name='intellievent'
    ),
    url(
        regex=r'aggregation/$',
        view=views.AggreationView.as_view(),
        name='aggregation'

    ),
    url(
        regex=r'aggregation/new/$',
        view=views.AggreationCreate.as_view(),
        name='create_aggregation'

    ),
    url(
        regex=r'aggregation/update/(?P<pk>\w*)/$',
        view=views.AggreationUpdate.as_view(),
        name='update_aggregation'

    ),
    url(
        regex=r'aggregation/delete/(?P<pk>\w*)/$',
        view=views.AggreationDelete.as_view(),
        name='delete_aggregation'

    ),
    url(
        regex=r'update_hgs/$',
        view=views.update_user_hgs,
        name='update_hgs'
    ),
    url(
        regex=r'get_network_usage/(?P<pk>\w*)/$',
        view=views.get_network_usage,
        name='get_network_usage'
    ),
    url(
        regex=r'set_stats_period/$',
        view=views.set_stats_period,
        name='set_stats_period'
    ),
    url(
        regex=r'get_filesystem_usage/(?P<pk>\w*)/$',
        view=views.get_filesystem_usage,
        name='get_filesystem_usage'
    ),

    url(
        regex=r'get_system_usage/(?P<pk>\w*)/$',
        view=views.get_system_usage,
        name='get_system_usage'
    ),


]
